<a href="https://colab.research.google.com/github/Gui-Coimbra/python_para_machine_learning/blob/main/introducao_pandas%26numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
alunos = {"nome":["Ricardo", "Pedro", "Jose", "Carlos"],
          "nota":[4, 7, 5.5, 9],
          "Aprovado":["Não","Sim","Não","Sim"]}

In [ ]:
print(alunos)

{'nome': ['Ricardo', 'Pedro', 'Jose', 'Carlos'], 'nota': [4, 7, 5.5, 9], 'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}


In [ ]:
dataFrame = pd.DataFrame(alunos)
print(dataFrame)

      nome  nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2     Jose   5.5      Não
3   Carlos   9.0      Sim


In [ ]:
dataFrame.head()

nome  nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2     Jose   5.5      Não
3   Carlos   9.0      Sim

In [ ]:
dataFrame.shape

(4, 3)

In [ ]:
dataFrame.describe()

nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000

In [ ]:
dataFrame['nome']

0    Ricardo
1      Pedro
2       Jose
3     Carlos
Name: nome, dtype: object

In [ ]:
dataFrame.loc[0:2]

nome  nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2     Jose   5.5      Não

In [ ]:
dataFrame.loc[ dataFrame['Aprovado'] == 'Sim' ]

nome  nota Aprovado
1   Pedro   7.0      Sim
3  Carlos   9.0      Sim

In [ ]:
DF2 = dataFrame.loc[ dataFrame['Aprovado'] == 'Sim' ]
print(DF2)

     nome  nota Aprovado
1   Pedro   7.0      Sim
3  Carlos   9.0      Sim


In [ ]:
DF3 = dataFrame.loc[dataFrame['Aprovado'] != "Sim"]
print(DF3)

      nome  nota Aprovado
0  Ricardo   4.0      Não
2     Jose   5.5      Não


In [ ]:
objeto1 = pd.Series([2,6,9,10,5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [ ]:
import numpy as np
array1 = np.array([6,12,2,9,10])
array2 = np.array([(2,6,9,10,5),(6,12,2,9,10)])
print(array1)
print(array2)

[ 6 12  2  9 10]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [ ]:
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     2
3     9
4    10
dtype: int64
