<a href="https://colab.research.google.com/github/Gui-Coimbra/python_para_machine_learning/blob/main/lambda_map_comprehesion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
kmh = [10, 40, 55, 62, 75, 80, 75, 103] 

In [ ]:
mph = list(map(lambda x: x/1.61, kmh))
print(mph)

[6.211180124223602, 24.844720496894407, 34.161490683229815, 38.50931677018633, 46.58385093167701, 49.689440993788814, 46.58385093167701, 63.9751552795031]


In [ ]:
mph2 = [x/1.61 for x in kmh]
print(mph2)

[6.211180124223602, 24.844720496894407, 34.161490683229815, 38.50931677018633, 46.58385093167701, 49.689440993788814, 46.58385093167701, 63.9751552795031]


In [ ]:
caracteres = [i for i in 'Guilherme Coimbra']
print(caracteres)

['G', 'u', 'i', 'l', 'h', 'e', 'r', 'm', 'e', ' ', 'C', 'o', 'i', 'm', 'b', 'r', 'a']


In [ ]:
x = lambda x: x/2
x(10)

5.0

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([(2,5,7),(5,3,9),(4,6,5)])
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [ ]:
c = np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
